channels:
- conda-forge
dependencies:
- python=3.12.12
- pip
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - ml-app-wind-draft==0.1
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.4.0
  - scipy==1.15.3
name: mlflow-env
